-- Create the table for sensor data
CREATE TABLE IF NOT EXISTS sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    timestamp TIMESTAMPTZ,
    device_id TEXT,
    status TEXT,
    basket_size TEXT,
    matrix_sensor_1 JSONB,
    level_sensor_1 FLOAT,
    matrix_sensor_2 JSONB,
    level_sensor_2 FLOAT,
    matrix_total JSONB,
    total_level FLOAT,
    gps JSONB,
    battery INTEGER
);

-- Optional: Create an index on device_id and timestamp for faster queries
CREATE INDEX IF NOT EXISTS idx_sensor_data_device_id ON sensor_data(device_id);
CREATE INDEX IF NOT EXISTS idx_sensor_data_timestamp ON sensor_data(timestamp);
